### ISSUE TITLE
ErrorException in GET /nova-api/metrics/transactions-per-day

### ISSUE THREAD

**Issue by georgeburdell** [RoboJackets/apiary#599] opened 2019-04-08 21:47 UTC
## Error in Apiary

**ErrorException** in **GET /nova-api/metrics/transactions-per-day**
A non-numeric value encountered

[View on Bugsnag](https://app.bugsnag.com/robojackets/apiary/errors/5cabc170d5deb20019266179?event_id=5cabc1700037e9922b2f0000&i=gh&m=ci)

## Stacktrace

    Nova/Metrics/PaymentsPerDay.php:19 - App\Nova\Metrics\PaymentsPerDay::calculate
    Http/Middleware/CASAuthenticate.php:58 - App\Http\Middleware\CASAuthenticate::handle

[View full stacktrace](https://app.bugsnag.com/robojackets/apiary/errors/5cabc170d5deb20019266179?event_id=5cabc1700037e9922b2f0000&i=gh&m=ci)

*Created by RoboJackets Admin via Bugsnag*

**Comment by kberzinch** [comment] 2019-04-08 22:06
Duplicate of #561

**Closed by kberzinch** 2019-04-08 22:06 UTC
Labels: type / bug
