### ISSUE TITLE
Add custom CSV exporters to Nova

### ISSUE THREAD

**Issue by JoshOldenburg** [RoboJackets/apiary#1388] opened 2020-10-01 21:09 UTC
#1308 removed the package form of Nova Excel exports. These should be replaced by a custom exporter (as already exists in some places) for simplicity.

Related to #1165

**Comment by JoshOldenburg** [comment] 2020-10-03 02:25
- Export Contact Info: `name`, `gt_email`, `personal_email`, `phone`
- Export Names and Emails: `preferred_first_name`, `last_name`, `gt_email`
- Export GTIDs: `first_name`, `last_name`, `gtid`
- Export Usernames: `uid`

**Comment by kberzinch** [comment] 2024-02-24 19:45
Duplicate of #898

**Closed by kberzinch** 2024-02-24 19:45 UTC
Labels: priority / high, type / feature, area / nova
