### ISSUE TITLE
Add support for Uptime Robot status monitoring

### ISSUE THREAD

**Issue by evan10s** [RoboJackets/apiary#372] opened 2018-05-24 22:13 UTC
In order to monitor the status of the production MyRoboJackets via Uptime Robot, we need a route similar to Nextcloud's [status.php](https://cloud.robojackets.org/status.php) that is accessible without authentication and indicates that the application is up and working.

**Comment by kberzinch** [comment] 2018-05-24 22:13
Duplicate of #81

**Closed by kberzinch** 2018-05-24 22:13 UTC
Labels: area / devOps, priority / medium, type / enhancement
